### ISSUE TITLE
OSM displays only on 0,0 180,90

### ISSUE THREAD

**Issue by mbasa-georepublic** [gtt-project/redmine_gtt#103]
The OSM Baselayer is displaying only in 0,0 180,90 coordinates. Other Baselayers (i.e. GSI maps) are displaying correctly beyond this coordinate area.

**Comment by dkastl** [comment]
Interesting. I quickly changed the tile server from  the Japanese`https://tile.openstreetmap.jp/{z}/{x}/{y}.png` to the global `https://tile.openstreetmap.org/{z}/{x}/{y}.png` and then the whole world seems to show up. So this is a problem (or feature) of the Japanese tile server, it seems.

**Comment by mbasa-georepublic** [comment]
verified that changing to openstreetmap.org fixes this issue.
