### ISSUE TITLE
[v2] Backport "main" branch updates to "2.1-stable" branch

### ISSUE THREAD

**Issue by sanak** [gtt-project/redmine_gtt#109]
Main differences are as follows:
- `main`
   - TypeScript + webpack
   - Delete jQuery (use DOM querySelector .etc instead)
   - Almost latest ol (6.5.0) and ol-ext (3.1.19) with types-ol-ext
- `2.1-stable`
   - Not created yet, but this should be created from commit:https://github.com/gtt-project/redmine_gtt/commit/3953592519a5eb59bd68e6639734cfaf140a9e65
   - Support jQuery (possible Windows 7 user)
   - Older ol (4.6.5) and ol-ext (1.1.3) with customize balloon shape

---

TBD:

**Comment by dkastl** [comment]
A good strategy would be to make this issue lowest priority and after a few months it can be closed because nobody cares about IE11 anymore ;-)

**Comment by sanak** [comment]
Just finished backport sync work...
I skipped map icon style change and plugin settings font symbol part.

Here is the memo of the work.
```bash
# 2021/05/20 21:06 - Upgraded gem pg default version from 1.1.4 to 1.2.2
git cherry-pick 78e36ed

# 2021/05/13 22:12 - Enlarged plugin settings icon size
git cherry-pick 6e282ad

# 2021/05/18 15:00 - Fixed reload font time error when empty geometry
git cherry-pick b12eca2

# 2021/05/18 15:59 - Fixed reload font issue when multi features exist
git cherry-pick 0b92a82

# 2021/05/18 17:45 - Made inverse polygon consistent
git cherry-pick e0f6d7f
# (Added additional fix condition)

# 2021/05/19 21:37 - Adjusted tracker icon settings css
git cherry-pick 7df0185

# 2021/09/14 17:19 - Added search icon for address search as gtt-icon
git cherry-pick 0653838

# 2021/09/14 17:19 - Fixed geocoding button in map panel
git cherry-pick 18e0eba

# 2021/09/14 22:43 - Fixed geolocation error
git cherry-pick 660cc84

# 2021/09/15 19:29 - Commented out unnecessary locale strings and adjusted ja locale
git cherry-pick d13349a

# 2021/09/15 19:29 - Configurable editable geometry types and geojson upload on issue map
git cherry-pick 6c8e9f2

# 2021/09/21 17:33 - Added ResizeObserver to detect map div resize event
git cherry-pick 8b6d292

# 2021/10/19 17:56 - Supported collapsible state of issues map
git cherry-pick 899eb30

# 2021/11/05 10:37 - Localize permission labels (#122)
git cherry-pick 847fd10

# 2021/11/08 12:02 - Limit deface app/overrides path to only gtt plugin
git cherry-pick c1f6adc
```

Close this issue, once.

**Comment by sanak** [comment]
Sync more
```bash
# 2021-11-13 20:40 - Separate reload patch timing
git cherry-pick 06e11c1

# 2021-11-19 21:11 - Configurable geocoding button visibility on map
git cherry-pick 5ee547a
```

Also, port the following commit from `2.1-stable` to `main` branch.
- https://github.com/gtt-project/redmine_gtt/commit/71e6f5fc617e0e381cb28a5f90824cec7b0d75c9 `Adjusted deface override original value and position`

**Comment by dkastl** [comment]
I think it would be better to upgrade MCR rather than back-porting. Shall we close this? Not sure this issue is still up-to-date anyway.

**Comment by sanak** [comment]
@dkastl I close this also.
