### ISSUE TITLE
Disable focus and auto scroll to issue note when editing issue

### ISSUE THREAD

**Issue by sanak** [gtt-project/redmine_gtt#112]
**Problem**
When editing issue, Redmine original behavior is focus and auto scroll to issue note, but this causes map panel be out of screen on mobile device.

**To Reproduce**
Start to edit existing issue.

**Expectation**
It is also possible to editing issue's geometry, so showing map is preferable on mobile device.

**Comment by dkastl** [comment]
Maybe on mobile screens while editing an issue the map could be hidden and would be expanded to full screen through a "Map" button?

**Comment by sanak** [comment]
> Maybe on mobile screens while editing an issue the map could be hidden and would be expanded to full screen through a "Map" button?

Maybe... In that case, some UI design will be necessary.

**Comment by sanak** [comment]
Well, I close this, once.
