### ISSUE TITLE
Selecting none geometry issue on issues list view causes error

### ISSUE THREAD

**Issue by sanak** [gtt-project/redmine_gtt#126]
**Problem**
When selecting none geometry issue on issues list view causes error.

**Expectation**
The error should not happen.

The error seems to happen at the following line.
https://github.com/gtt-project/redmine_gtt/blob/main/src/components/gtt-client.ts#L300

**Comment by dkastl** [comment]
@sanak , does [this](https://github.com/gtt-project/redmine_gtt/commit/4d3706be1bbe699cc64a779a85f46c0343dda21d) solve the issue?
