### ISSUE TITLE
Incompatibility with v2 in "src/components/gtt-client.ts"

### ISSUE THREAD

**Issue by sanak** [gtt-project/redmine_gtt#128]
**Problem**
This make difficult to sync main (current v3) and v2.

- [ ] v3 `this.contents` type is `string`, although v2 `contents` is object.
  - v3: `this.contents = options.target.dataset`
  - v2: `$(options.target).data();`

**Comment by dkastl** [comment]
I think it would be better to upgrade MCR rather than back-porting. Shall we close this?

**Comment by sanak** [comment]
@dkastl Yes, I close this.
Thanks for notice.
