### ISSUE TITLE
Load default tile source with migration

### ISSUE THREAD

**Issue by dkastl** [gtt-project/redmine_gtt#133]
It would be good to have a default tile source setup when adding the GTT plugin, and OSM as a tile source would be a good default:

- Name: `OSM`
- Type: `ol.source.OSM`
- Globally available: `checked`
- Default for new projects: `checked`
- Options:
```
{
  "url": "https://tile.openstreetmap.jp/{z}/{x}/{y}.png",
  "custom": "19/34.74701/135.35740",
  "crossOrigin": null,
  "attributions": "<a href=\"https://www.openstreetmap.org/copyright\">OpenStreetMap</a>"
}
```

See example in: https://github.com/HugoHasenbein/redmine_attachment_categories/blob/master/db/migrate/015_create_attachment_categories.rb

**Comment by sanak** [comment]
Okay, I will try that, later.

**Comment by dkastl** [comment]
In this commit I add a notification to tell users that no basemap has been configured yet. I think this is sufficient. Also not having a map layer does not prevent the OpenLayers DIV to load and show icons, etc..
https://github.com/gtt-project/redmine_gtt/commit/bea28644b68a45966707ec5c1afc69524b0dd127

![image](https://user-images.githubusercontent.com/227762/231928373-41e067a9-af15-4827-9317-d667395ea228.png)
