### ISSUE TITLE
Use Material Icons

### ISSUE THREAD

**Issue by dkastl** [gtt-project/redmine_gtt#164]
**Problem**
There are too many icon fonts provided at the moment. 

**Improvement**
Let's just use Material Icons: https://github.com/google/material-design-icons

**Comment by sanak** [comment]
@dkastl Well, font name difference seems to be the cause of font rendering issue on map.
Adding space to font and name solved the issue on my local environment, so could you try it ?
```diff
--- a/src/fonts/MaterialDesignDef.js
+++ b/src/fonts/MaterialDesignDef.js
@@ -1,8 +1,8 @@
 import ol_style_FontSymbol from 'ol-ext/style/FontSymbol'
 
 ol_style_FontSymbol.addDefs(
-{      "font":"MaterialIcons",
-       "name":"MaterialIcons",
+{      "font":"Material Icons",
+       "name":"Material Icons",
        "copyright":"Apache-2.0",
        "prefix": "mdi"
 },
```

By the way, over 2200 fonts amount is really huge...
