### ISSUE TITLE
Visibility of lines and polygons on high zoom levels

### ISSUE THREAD

**Issue by dkastl** [gtt-project/redmine_gtt#166]
**Problem**
On higher zoom levels lines and polygons will become invisible. 
Especially in projects with large extent this happens when the map zooms to full extent of all issues.

**Improvement**
The following alternatives could solve the problem:
1. Show marker with line/polygon icon at center point of the geometry on high zoom levels
2. Limit max. zoom level
3. Hide issues from a certain zoom level (and notify the user to zoom in more to see issues on the map)

**Comment by sanak** [comment]
@dkastl Okay, thanks for the information.
I will try to check it, once.

**Comment by dkastl** [comment]
file:///home/daniel/Videos/Screencasts/Screencast%20from%202023-05-16%2014-20-54.webm

**Comment by dkastl** [comment]
https://github.com/gtt-project/redmine_gtt/assets/227762/d6bdddb3-ed15-47cd-9929-1d096e4619ad
