### ISSUE TITLE
Icon for user marker

### ISSUE THREAD

**Issue by dkastl** [gtt-project/redmine_gtt#167]
**Problem**
There is no icon set for users.

![Screenshot from 2022-08-03 15-09-55](https://user-images.githubusercontent.com/227762/182536571-0ed4ce44-d8cd-4d7e-b42d-566aa02448d5.png)

**To Reproduce**
Go to `/my/account` and see the user location icon.

**Expectation**
Show a "person" icon for example: https://fonts.google.com/icons?selected=Material+Symbols+Outlined:person:FILL@0;wght@400;GRAD@0;opsz@48

**Comment by sanak** [comment]
Okay, thanks for fixing this! 🙇‍♂️
