### ISSUE TITLE
Publish `redmine_gtt` plugin:

### ISSUE THREAD

**Issue by dkastl** [gtt-project/redmine_gtt#2]
- [x] use branch `main`
- [x] has branch `develop`
- [x] has tests (if not create issue)
- [ ] has CI with GH Actions (if not create issue)
- [x] has `LICENSE`
- [x] has `README.md`
- [x] comments are in English (if not create issue)

**Comment by sanak** [comment]
Test issue is already created in #23, so I close this issue.
