### ISSUE TITLE
GH Actions fails with test (test_should_validate_invalid_multipolygon_geometry)

### ISSUE THREAD

**Issue by dkastl** [gtt-project/redmine_gtt#209]
It seems that the test for invalid multi-polygon makes GH actions fail:

```
........................................................F

Failure:
UpdateProjectSettingsTest#test_should_validate_invalid_multipolygon_geometry [/__w/redmine_gtt/redmine_gtt/redmine/plugins/redmine_gtt/test/unit/update_project_settings_test.rb:34]:
Expected true to be nil or false

rails test plugins/redmine_gtt/test/unit/update_project_settings_test.rb:19

........

Finished in 4.933351s, [13](https://github.com/gtt-project/redmine_gtt/actions/runs/4076204591/jobs/7023623162#step:14:14).[17](https://github.com/gtt-project/redmine_gtt/actions/runs/4076204591/jobs/7023623162#step:14:18)56 runs/s, 71.9592 assertions/s.
65 runs, 355 assertions, 1 failures, 0 errors, 0 skips
Error: Process completed with exit code 1.
```

See for example: https://github.com/gtt-project/redmine_gtt/actions/runs/4076204591/jobs/7023623162

@sanak , I tried to change the coordinates to submit an invalid geometry, but without success. The test still did not pass, so I'm not sure I understand this test correctly.

Do you know how to fix this?

**Comment by sanak** [comment]
@dkastl Oh, I missed this issue.
The error seems to start from yesterday, so something dependencies change may cause this issue.
I will take a look at it today.

**Comment by sanak** [comment]
@dkastl 
I checked the diff between the following actions, and there seems to be rgeo update
- 1/10 - Passed: https://github.com/gtt-project/redmine_gtt/actions/runs/3881650952/jobs/6620893470
  - Installing rgeo 2.4.0 with native extensions
- 2/2 - Failed: https://github.com/gtt-project/redmine_gtt/actions/runs/4071281842/jobs/7012941361
  - Installing rgeo 3.0.0 with native extensions

rgeo 3.0.0 seems to be released at 1/25 (last week),
https://github.com/rgeo/rgeo/releases/tag/v3.0.0

and rgeo 2.4.0 <-> 3.0.0 diffs are too much...
https://github.com/rgeo/rgeo/compare/v2.4.0...v3.0.0

The easiest fix will be adding `GEM_RGEO_VERSION` environment variable like others, and limit its value to `2.4.0`, but is it enough as a quick workaround ?

**Comment by sanak** [comment]
Oh, yes. I also found the doc.
I will create another issue to upgrade rgeo later.

**Comment by sanak** [comment]
Well, rgeo seems not to have rails version dependencies, so I just set `2.4.0` as workaround.
