### ISSUE TITLE
Test workflow (GH Actions)

### ISSUE THREAD

**Issue by dkastl** [gtt-project/redmine_gtt#23]
Add a workflow for automated testing with GH Actions.

**Comment by sanak** [comment]
The followings will be quite useful as reference.
- https://github.com/redmine-patch-meetup/redmine-dev-mirror/blob/develop/.github/workflows/test.yml
- https://github.com/jbbarth/redmine_drafts/blob/master/.github/workflows/master.yml

**Comment by sanak** [comment]
I will restart this work with creating new `test-postgis.yml` by referring `test-postgres.yml`.
- https://github.com/gtt-project/redmine_text_blocks/pull/26
