### ISSUE TITLE
When Tracker changed, map will be blank

### ISSUE THREAD

**Issue by smellman** [gtt-project/redmine_gtt#257]
**Problem**

In issue edit view, when Tracker changed, map will be blank.

**To Reproduce**

1. Access to issue edit view.
2. Change Tracker type.
3. Map will be blank.

**Expectation**

**Screenshots**

<img width="1244" alt="スクリーンショット 2023-10-10 5 52 36" src="https://github.com/gtt-project/redmine_gtt/assets/135112/a53adf74-a81e-4058-8cae-9486590f53a9">
<img width="1259" alt="スクリーンショット 2023-10-10 5 52 47" src="https://github.com/gtt-project/redmine_gtt/assets/135112/9ee5bdb2-2f60-48ea-bb07-f47d710b403f">

**Platform/smartphone:**

 - Device: macOS
 - OS: Sonome
 - App Version: Firefox 118.0.1

**Comment by smellman** [comment]
It produces when change Project, Status and Priority.
Reload map function may be break.

**Comment by dkastl** [comment]
Thanks for the fix!
