### ISSUE TITLE
Map Layers editing order becomes incorrect when adding new one

### ISSUE THREAD

**Issue by sanak** [gtt-project/redmine_gtt#274]
**Problem**
Currently, newly added map layer position become first, but later position editing becomes incorrect.

**To Reproduce**
1. Add new map layer from http://localhost:3000/gtt_map_layers
   * The position becomes first
2. Edit order by drag and drop right green arrows.
3. Reload browser, then order becomes incorrect (unexpected result)

**Expectation**
* Newly added map layer position should be last.
* Order should be correct always.

**Screenshots**
![redmine_gtt-invalid-map-layers-position](https://github.com/gtt-project/redmine_gtt/assets/629923/024aa82c-f646-4b61-bfc5-2eff121d0f78)

**Environment:**
 - OS: macOS 14.4.1
- Ruby Version: `3.2.1` (via asdf)
- Redmine Branch: `5.1-stable`
- Plugin Branch: `next`

**Comment by dkastl** [comment]
I think this is closed, no?
