### ISSUE TITLE
WMTS format

### ISSUE THREAD

**Issue by CtrlMajSup** [gtt-project/redmine_gtt#281]
Hello,

I would like to know how to fill in the map layer creation form in the case of a wmts type source.
I have no idea what information to enter in the form and I haven't found any examples. The request for the map is as follows: 

`https://www.domaine.com./wmts?layer=LAYER:DEEP&style=&tilematrixset=EPSG:4326&Service=WMTS&Request=GetTile&Version=1.0.0&Format=image/jpeg&TileMatrix=EPSG:4326:{z}&TileCol={x}&TileRow={y}`

Thank you in advance for your help

**Comment by dkastl** [comment]
You basically provide the configuration in the same way as you would do when you add a layer to OpenLayers: https://openlayers.org/en/latest/apidoc/module-ol_source_WMTS-WMTS.html

As "Layer type" you select `Tile` and probably don't need to configure "Layer options". An empty `{}` would be fine.

That said, in any of the options you can only provide `"key": "value"` pairs, but you couldn't add something like 

```
"tileGrid": new WMTSTileGrid({
  ...
}),
```

... which might be necessary for layer type WMTS. So if it's necessary, then at the moment you couldn't add your WMTS layer and some more thought had to be put into how to specify a WMTSTileGrid.

**Comment by CtrlMajSup** [comment]
first of all, thank you for your help 
But in this case the WMTS option in the form's source type is supposed to be filled in how?

I'll try to work around the problem with a mapproxy.

**Comment by dkastl** [comment]
You can confirm, if your can show your layer in OpenLayers with something like

```javaascript
import 'ol/ol.css';
import { Map, View } from 'ol';
import TileLayer from 'ol/layer/Tile';
import WMTS from 'ol/source/WMTS';
import { get as getProjection } from 'ol/proj';
import WMTSTileGrid from 'ol/tilegrid/WMTS';

// WMTS source configuration
const wmtsSource = new WMTS({
  url: 'https://www.domaine.com/wmts?',
  layer: 'LAYER:DEEP',
  matrixSet: 'EPSG:4326',
  format: 'image/jpeg',
  projection: getProjection('EPSG:4326'),
  tileGrid: new WMTSTileGrid({
    origin: [-180, 90], // Origin of the grid
    resolutions: [
      0.703125, 0.3515625, 0.17578125, 0.087890625, 0.0439453125, 0.02197265625, 0.010986328125, 0.0054931640625,
      0.00274658203125, 0.001373291015625, 0.0006866455078125, 0.00034332275390625, 0.000171661376953125, 0.0000858306884765625
    ], // Resolutions for each zoom level
    matrixIds: [
      'EPSG:4326:0', 'EPSG:4326:1', 'EPSG:4326:2', 'EPSG:4326:3', 'EPSG:4326:4', 'EPSG:4326:5', 'EPSG:4326:6', 'EPSG:4326:7',
      'EPSG:4326:8', 'EPSG:4326:9', 'EPSG:4326:10', 'EPSG:4326:11', 'EPSG:4326:12', 'EPSG:4326:13'
    ] // Matrix IDs for each zoom level
  }),
  style: '', // Specify the style if needed
  wrapX: true // Wraps the world horizontally
});

// WMTS layer configuration
const wmtsLayer = new TileLayer({
  source: wmtsSource
});

// Map configuration
const map = new Map({
  target: 'map', // The ID of the element to render the map in
  layers: [
    wmtsLayer
  ],
  view: new View({
    projection: 'EPSG:4326',
    center: [0, 0],
    zoom: 2
  })
});
```

Then the `wmtsSource` options object would be what you need to use in "Source options".
The problematic part is the TileGrid configuration.

**Comment by CtrlMajSup** [comment]
Yes, it works. I was using it before I knew about this plugin.

**Comment by dkastl** [comment]
I wasn't aware that WMTS seems to require a tilegrid setting. The redmine_gtt plugin stores the options in jsonb format, so settings must comply with JSON syntax.

We could extend the map layer implementation and add tilegrid configuration similar to how the format options exist. But that would take a bit of time for implementation and testing. contributions are of course welcome.

**Comment by CtrlMajSup** [comment]
Thank you very much for your clarification. 

I continued with my mapproxy idea. If anyone else is wondering, I set up a mapproxy service configured to retrieve my WMTS tiles and then I used the mapproxy API in the plugin with the following config:

`layer type: tile` and `source type: xyz`
