### ISSUE TITLE
Remove Geocoder from map toolbar if not enabled

### ISSUE THREAD

**Issue by dkastl** [gtt-project/redmine_gtt#29]
The Geocoder toolbar icon is still visible even if the Geocoder configuration is empty.

**Comment by sanak** [comment]
This seems to be done already, but I will check it, again.

**Comment by sanak** [comment]
@dkastl  
I confirmed that this is implemented in the following lines, but I felt that using ol-ext Search control is better UI/UX.
- https://viglino.github.io/ol-ext/examples/search/map.control.search.html

I will close this issue, then create new enhancement issue for ol-ext Search control.

**Comment by dkastl** [comment]
OK
