### ISSUE TITLE
CI variables are not documented and cause fork repository's CI error

### ISSUE THREAD

**Issue by sanak** [gtt-project/redmine_gtt#302]
**Problem**
From PR:#266, following variables are introduced in `next` branch,
* `PLUGIN_TEST_MATRIX_REDMINE_VERSION`
* `PLUGIN_TEST_MATRIX_RUBY_VERSION`

but both variables are not documented and cause fork repository's CI error without fork repository/organization side setting.
https://github.com/sanak/redmine_gtt/actions/runs/9336681582
```
[Test with PostGIS](https://github.com/sanak/redmine_gtt/actions/runs/9336681582/workflow)
Error when evaluating 'strategy' for job 'test'. .github/workflows/test-postgis.yml (Line: 27, Col: 26): 
Error parsing fromJson,.github/workflows/test-postgis.yml (Line: 27, Col: 26): 
Error reading JToken from JsonReader. Path '', line 0, position 0.,.github/workflows/test-postgis.yml (Line: 27, Col: 26): 
Unexpected value '',.github/workflows/test-postgis.yml (Line: 28, Col: 23): 
Error parsing fromJson,.github/workflows/test-postgis.yml (Line: 28, Col: 23): 
Error reading JToken from JsonReader. Path '', line 0, position 0.,.github/workflows/test-postgis.yml (Line: 28, Col: 23): 
Unexpected value ''
```

**To Reproduce**
Push `next` branch to fork repository.

**Expectation**
CI should always succeed, even on a forked repository.

**Alternatives**
Alternative is reverting back to original way and I personally prefer this way.
```diff
--- a/.github/workflows/test-postgis.yml
+++ b/.github/workflows/test-postgis.yml
@@ -24,8 +24,8 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        redmine_version: ${{ fromJSON(vars.PLUGIN_TEST_MATRIX_REDMINE_VERSION) }}
-        ruby_version: ${{ fromJSON(vars.PLUGIN_TEST_MATRIX_RUBY_VERSION) }}
+        redmine_version: ["5.0-stable", "5.1-stable", "master"]
+        ruby_version: ["3.0", "3.1", "3.2"]
```

**Comment by dkastl** [comment]
I see. That's indeed a bit annoying.
Just wondering, if there is another way to specify these matrix variables across multiple repositories. Because that's the main purpose.

**Comment by dkastl** [comment]
Do you think it would be a good idea to create our own Github Actions extension for this?

**Comment by dkastl** [comment]
Just found a new project setting up Redmine. Maybe we can use it contribute improvements, if necessary: https://github.com/marketplace/actions/setup-redmine

**Comment by dkastl** [comment]
And there is another one https://github.com/two-pack/redmine-plugin-test-action

**Comment by sanak** [comment]
> Just found a new project setting up Redmine. Maybe we can use it contribute improvements, if necessary: https://github.com/marketplace/actions/setup-redmine

Well, this one seems to support system (UI) test, so using this one may be better for us.

**Comment by sanak** [comment]
> I see. That's indeed a bit annoying. Just wondering, if there is another way to specify these matrix variables across multiple repositories. Because that's the main purpose.

But, personally, sharing matrix is not good, because it depends on each plugin.
(For example, `redmine_gtt` plugin supports only PostgreSQL/PostGIS, but other none geometry related plugins can support other databases.)
So, matrix part will be various.

In case of using above `actions/setup-redmine`, we need to extend PostGIS for `redmine_gtt` plugin.
https://github.com/hidakatsuya/action-setup-redmine/blob/main/action.yml#L75-L97

Shall we create PR for PostGIS ?

**Comment by sanak** [comment]
Well, I add PR diffs which use above `actions/setup-redmine`.
* https://github.com/redmica/redmine_ip_filter/pull/46/files
* https://github.com/redmica/redmine_issues_panel/pull/55/files

I think that using matrix `include` is also good way to reduce unnecessary combinations. 😊

**Comment by sanak** [comment]
Well, currently magic variables (`PLUGIN_TEST_MATRIX_REDMINE_VERSION`, `PLUGIN_TEST_MATRIX_RUBY_VERSION`) were deleted from `next` branch in the following commit, so I close this issue.
* https://github.com/gtt-project/redmine_gtt/commit/cf0d3de762f1ade3349e39654e98c2bb871fb493

About switching to `actions/setup-redmine`, I will create a new issue.
