### ISSUE TITLE
Custom fields view's up-down arrow icon is missing

### ISSUE THREAD

**Issue by sanak** [gtt-project/redmine_gtt#41]
**Problem**
up-down arrow icon is missing in Custom fields view (`/custom_fields`).

**To Reproduce**
Install `redmine_gtt` plugin.

**Expectation**
up-down arrow icon should be shown.

**Screenshots**
With GTT plugin:
![custom_fields_missing_updown_arrow_icon_with_gtt](https://user-images.githubusercontent.com/629923/111272532-1adebd00-8676-11eb-99dc-17f53550326d.png)

Without any plugins:
![custom_fields_missing_updown_arrow_icon_with_raw](https://user-images.githubusercontent.com/629923/111274648-97729b00-8678-11eb-86cc-b8428182745c.png)

**Platform/smartphone:**
 - Device: MacBook Pro (15-inch, 2018)
 - OS: macOS Catalina (10.15.7)
 - App Version:
    - Redmine GTT Plugin 2.0.2
    - Chrome (latest)

**Comment by dkastl** [comment]
I guess it's similar to the icon missing to show and hide the map fieldset on the issues page.
Probably there has been some change with recent Redmica

**Comment by dkastl** [comment]
I think this is also a problem in `fonts.css` ... maybe it's the namespace of the icon set, that causes problems
