### ISSUE TITLE
Settings for collapsible state of issues map

### ISSUE THREAD

**Issue by dkastl** [gtt-project/redmine_gtt#47]
Currently the issues map of a project is collapsed by default, which makes many users even unaware of the map.

Since some user may want to show the map by default and some want to have it hidden by default, it would be good to have settings for that, eventually even on a project or user level, if that's not too hard.

- [x] Global plugin settings (checkbox) to expand the issues page map by default 
- [ ] optional: Project settings (checkbox on GTT tab) to expand the issues page map by default (overrides gloabl settings)

**Comment by sanak** [comment]
Related issue/PR:
- #60
- #62
