### ISSUE TITLE
Zoom to "all issues" extent on issues page

### ISSUE THREAD

**Issue by dkastl** [gtt-project/redmine_gtt#51]
The issues map should zoom to the extent of all visible issues, and if there is no issue to the project polygon extent (if available).

![Screenshot from 2021-03-23 15-34-17](https://user-images.githubusercontent.com/227762/112103697-73213c00-8bed-11eb-97be-843dda86a876.png)

At the moment it zooms to default location.

**Comment by smellman** [comment]
Fixes it with #56 PR.
