### ISSUE TITLE
Feature popup misplacement

### ISSUE THREAD

**Issue by dkastl** [gtt-project/redmine_gtt#52]
When clicking on an issue on the map, the placemment of the popup label is wrong:

![Screenshot from 2021-03-23 15-36-23](https://user-images.githubusercontent.com/227762/112103821-ac59ac00-8bed-11eb-98f1-a7a55039562b.png)

There are also two arrows pointing down, so eventually something has changed with OL-ext API.

**Comment by smellman** [comment]
Fixes it with #56 PR.
