### ISSUE TITLE
Setting for overview map collapsed by default

### ISSUE THREAD

**Issue by dkastl** [gtt-project/redmine_gtt#61]
In MCR the request was to collapse the map on project issues list by default. 
Many users eventually don't reallize now that the map exists at all, so showing by default is better.

Instead it would be better to make this a setting:

- [ ] on global selev
- [ ] on project level

**Comment by sanak** [comment]
@dkastl  
This seems to be duplicate with #47, so I am thinking to close this.

**Comment by dkastl** [comment]
Yes, it's duplicate. Thanks for checking this.
