### ISSUE TITLE
Icon color does not reflect status on issue list map

### ISSUE THREAD

**Issue by dkastl** [gtt-project/redmine_gtt#63]
The color setting depending on the issue status is not applied in the issue list map:

![Screenshot from 2021-03-26 14-07-32](https://user-images.githubusercontent.com/227762/112585231-c3daa400-8e3c-11eb-8c11-f4f968e631ef.png)

![Screenshot from 2021-03-26 14-08-18](https://user-images.githubusercontent.com/227762/112585236-c6d59480-8e3c-11eb-99c8-078d51df72b7.png)

**Comment by smellman** [comment]
fixed with PR #64
