### ISSUE TITLE
Set fill color from tracker status color with alpha (0.1 or 0.2)

### ISSUE THREAD

**Issue by sanak** [gtt-project/redmine_gtt#77]
From https://github.com/gtt-project/redmine_gtt/issues/59#issuecomment-842851004
> Also, I noticed that polygon fill color is always same value `rgba(255, 136, 0, 0.2)` value, but is it better to use `stroke color with alpha 0.2` as fill color for example ?  
![geometry_styles](https://user-images.githubusercontent.com/629923/118594594-ad214f80-b7e4-11eb-925a-2a0b1fd9b22d.png)  
![plugin_status_color](https://user-images.githubusercontent.com/629923/118594616-b3173080-b7e4-11eb-8cea-eaf8ac3e89b0.png)

**Improvement**
Set fill color from tracker status color with alpha (0.1 or 0.2).

**Comment by dkastl** [comment]
Good idea to also adjust the fill color.
