### ISSUE TITLE
Set tracker icon default to empty

### ISSUE THREAD

**Issue by sanak** [gtt-project/redmine_gtt#83]
**Problem**
Currently, plugin settings tracker icon default is 1st item (`maki-bicycle`), but it should be empty (not selected) item.

**To Reproduce**
Create database from scratch.

**Screenshots**
![default_tracker_icon](https://user-images.githubusercontent.com/629923/118956030-35952100-b99a-11eb-83f0-f084b05bb42d.png)

**Comment by sanak** [comment]
Well, this seems not to be fixed in docker-gtt, so I reopen this.

**Comment by sanak** [comment]
I might patch wrong way about this, so checking history seems to become necessary.
https://github.com/gtt-project/redmine_gtt/commits/main/src/components/gtt-setting.ts

**Comment by sanak** [comment]
Okay, I will check above, later.
Thanks for advice.

**Comment by dkastl** [comment]
@sanak , could you check, if this is still a problem?

**Comment by sanak** [comment]
@dkastl Well, I think that this has been already solved, so I close this.
