### ISSUE TITLE
Issues with multiple basemap layers

### ISSUE THREAD

**Issue by dkastl** [gtt-project/redmine_gtt#93]
**Problem**

When multiple basemap layers are configured, these layers don't show up as expected.

**To Reproduce**
- Create multiple basemaps
- got to user account map (or others)
- no basemap is loaded by default

**Expectation**
There should be multiple maps to choose from with a default one loaded.

**Comment by sanak** [comment]
Okay. Probably, I missed something during webpack branch merge, so let me check this.
