### ISSUE TITLE
Support vector tile layers

### ISSUE THREAD

**Issue by dkastl** [gtt-project/redmine_gtt#97]
OpenLayers supports vector tiles, so it would be nice to make them also available in GTT.

To be discussed:

- how to apply styles
- layer configuration applicable?

Should support:

- [ ] https://github.com/openlayers/ol-mapbox-style#applyStyle
- [ ] https://openlayers.org/en/latest/apidoc/module-ol_layer_MapboxVector-MapboxVectorLayer.html and https://openlayers.org/workshop/en/vectortile/bright.html
- [ ] https://github.com/gsi-cyberjapan/gsimaps-vector-experiment
- [ ] https://qiita.com/cieloazul310/items/8999c88f1acf79632cd3

**Comment by sanak** [comment]
Oh, yes. I just think about this after #96. :smile:

**Comment by sanak** [comment]
Okay, great!
I confirmed that vector tiles (`*.pbf`) are loaded in my local project GTT setting.
And I was surprised that `style.json` can specify multiple sources. 😅

**Comment by sanak** [comment]
Well, `migu*` fonts seem to be defined in https://tile.openstreetmap.jp/styles/osm-bright-ja/style.json - `layers[*]/layout/text-font[0]`, so I guess that something font loading skipping setting may be necessary.

**Comment by smellman** [comment]
@dkastl How about you use MapboxVectorLayer?
API: https://openlayers.org/en/latest/apidoc/module-ol_layer_MapboxVector-MapboxVectorLayer.html
example: https://openlayers.org/en/latest/examples/mapbox-vector-layer.html

Sample: 
```javascript
const map = new Map({
  target: 'map',
  layers: [
    new MapboxVector({
      styleUrl: 'https://tile.openstreetmap.jp/styles/osm-bright/style.json'
    }),
  ],
  view: new View({
    center: [0, 0],
    zoom: 2,
  }),
});
```
